//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSCOM.DDA.UnitTest {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class DDAUnitTest : global::System.Configuration.ApplicationSettingsBase {
        
        private static DDAUnitTest defaultInstance = ((DDAUnitTest)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DDAUnitTest())));
        
        public static DDAUnitTest Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://msitvstf1:8080/tfs/")]
        public string TFSServer {
            get {
                return ((string)(this["TFSServer"]));
            }
            set {
                this["TFSServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TPC1")]
        public string TFSProjectCollection {
            get {
                return ((string)(this["TFSProjectCollection"]));
            }
            set {
                this["TFSProjectCollection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSIT1TPC1Project1")]
        public string TFSProject {
            get {
                return ((string)(this["TFSProject"]));
            }
            set {
                this["TFSProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEMO.values")]
        public string EnvironmentValues {
            get {
                return ((string)(this["EnvironmentValues"]));
            }
            set {
                this["EnvironmentValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoadWorkItemsFromFile {
            get {
                return ((bool)(this["LoadWorkItemsFromFile"]));
            }
            set {
                this["LoadWorkItemsFromFile"] = value;
            }
        }
    }
}
