//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSCOM.DDA {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class APP : global::System.Configuration.ApplicationSettingsBase {
        
        private static APP defaultInstance = ((APP)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new APP())));
        
        public static APP Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string logFilePath {
            get {
                return ((string)(this["logFilePath"]));
            }
            set {
                this["logFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Box")]
        public string loggingOption {
            get {
                return ((string)(this["loggingOption"]));
            }
            set {
                this["loggingOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mscomvstf:8080/tfs/mscom")]
        public string tfsServer {
            get {
                return ((string)(this["tfsServer"]));
            }
            set {
                this["tfsServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSCOM CSP")]
        public string tfsProjectName {
            get {
                return ((string)(this["tfsProjectName"]));
            }
            set {
                this["tfsProjectName"] = value;
            }
        }
    }
}
