//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSCOM.Test.Tools {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class WorkItemsMigrate : global::System.Configuration.ApplicationSettingsBase {
        
        private static WorkItemsMigrate defaultInstance = ((WorkItemsMigrate)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WorkItemsMigrate())));
        
        public static WorkItemsMigrate Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mscomvstf:8080/tfs")]
        public string TFSServerOriginal {
            get {
                return ((string)(this["TFSServerOriginal"]));
            }
            set {
                this["TFSServerOriginal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RXDPartner")]
        public string TFSProjectOriginal {
            get {
                return ((string)(this["TFSProjectOriginal"]));
            }
            set {
                this["TFSProjectOriginal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("original_Id")]
        public string OriginalIdList {
            get {
                return ((string)(this["OriginalIdList"]));
            }
            set {
                this["OriginalIdList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("original_Details")]
        public string OriginalDetails {
            get {
                return ((string)(this["OriginalDetails"]));
            }
            set {
                this["OriginalDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OPX")]
        public string ProductName {
            get {
                return ((string)(this["ProductName"]));
            }
            set {
                this["ProductName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://msitvstf1:8080/tfs")]
        public string TFSServerNew {
            get {
                return ((string)(this["TFSServerNew"]));
            }
            set {
                this["TFSServerNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSIT1TPC1Project1")]
        public string TFSProjectNew {
            get {
                return ((string)(this["TFSProjectNew"]));
            }
            set {
                this["TFSProjectNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSCOM")]
        public string TFSProjectCollectionOriginal {
            get {
                return ((string)(this["TFSProjectCollectionOriginal"]));
            }
            set {
                this["TFSProjectCollectionOriginal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TPC1")]
        public string TFSProjectCollectionNew {
            get {
                return ((string)(this["TFSProjectCollectionNew"]));
            }
            set {
                this["TFSProjectCollectionNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("outPut_Validate.html")]
        public string OutPutHTML {
            get {
                return ((string)(this["OutPutHTML"]));
            }
            set {
                this["OutPutHTML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CreateHTMLOnValidate {
            get {
                return ((bool)(this["CreateHTMLOnValidate"]));
            }
            set {
                this["CreateHTMLOnValidate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fields_to_migrate")]
        public string FieldsToMigrateFileName {
            get {
                return ((string)(this["FieldsToMigrateFileName"]));
            }
            set {
                this["FieldsToMigrateFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("migrated_Paired_Id")]
        public string UpdatePairedIdList {
            get {
                return ((string)(this["UpdatePairedIdList"]));
            }
            set {
                this["UpdatePairedIdList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test Case")]
        public string WorkItemType {
            get {
                return ((string)(this["WorkItemType"]));
            }
            set {
                this["WorkItemType"] = value;
            }
        }
    }
}
